spring:
  application:
    name: bikeshop-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/veloservice_db
    username: velo_user
    password: velo_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
server:
  port: 8080
  servlet:
    context-path: /api/v1
jwt:
  secret: ${JWT_SECRET:cambiaEstaClaveEnProduccionPorUnaMuyLargaDe32CharsMin}
  expiration: 86400000
  reset-expiration: 900000
app:
  reset-password-url: ${RESET_PASSWORD_URL:http://localhost:3000/reset-password}
resend:
  api-key: ${RESEND_API_KEY:}
  from: ${RESEND_FROM:}
  base-url: https://api.resend.com
logging:
  level:
    org.springframework.security: DEBUG
    com.bikeshop.manager: DEBUG
